import type {
  SkyCondition,
  Species,
  StructureType,
  WaterType,
} from '@/types';

/** How aggressive a presentation is — matched against the day's bite mood. */
export type Presentation = 'aggressive' | 'neutral' | 'finesse';

/**
 * Key into the in-app vector illustration for a bait. Several baits that look
 * alike to a new angler share one drawing (e.g. all paddletails). Kept here,
 * next to the data, so {@link LureArt} stays a pure switch on these strings.
 */
export type ArtKey =
  | 'lipless'
  | 'crankbait'
  | 'jerkbait'
  | 'spinnerbait'
  | 'buzzbait'
  | 'inline-spinner'
  | 'chatterbait'
  | 'spoon'
  | 'topwater-walker'
  | 'popper'
  | 'frog'
  | 'jig'
  | 'football-jig'
  | 'bucktail'
  | 'bladebait'
  | 'paddletail'
  | 'worm-texas'
  | 'wacky'
  | 'ned'
  | 'shakyhead'
  | 'dropshot'
  | 'carolina'
  | 'grub'
  | 'tube'
  | 'popping-cork'
  | 'bottom-rig'
  | 'slip-bobber'
  | 'shrimp'
  | 'baitfish'
  | 'worm-night'
  | 'crayfish'
  | 'crab'
  | 'cricket'
  | 'dough'
  | 'sandflea';

export interface LureEntry {
  name: string;
  category: 'lure' | 'rig' | 'bait';
  /** Suggested colors, sizes, retrieve. */
  details: string;
  /**
   * Plain-language "how to actually fish it" for a new angler — the retrieve or
   * technique in one or two sentences. This is the teaching layer.
   */
  howTo: string;
  /** Which illustration to show next to it. */
  art: ArtKey;
  waterTypes: WaterType[];
  /** Structures/cover where this shines. Empty = works anywhere. */
  structures: StructureType[];
  /** Ideal surface water-temp window (degrees F). */
  minWaterF: number;
  maxWaterF: number;
  /** Skies where this is strongest. Empty = sky-agnostic. */
  skies: SkyCondition[];
  presentation: Presentation;
  /** Intrinsic versatility 0-1; nudges ties toward proven producers. */
  baseScore: number;
  /** Short clause used when explaining the pick, e.g. "covers water fast". */
  strength: string;
  /**
   * Species this especially produces for. Omitted = broadly applicable (no
   * species bias). When a target species is set, listed lures get a boost and
   * species-specific lures that don't list it are de-prioritized.
   */
  species?: Species[];
  /**
   * Subtle / natural presentations that excel on heavily pressured, educated
   * fish. Boosted when the user marks the water as pressured.
   */
  pressureFriendly?: boolean;
  /**
   * High-vibration, flashy, loud, or scent-heavy baits fish can find in
   * stained/muddy water. Boosted in dirty water, downgraded in gin-clear.
   */
  dirtyWaterFriendly?: boolean;
}

/**
 * A compact but opinionated knowledge base. Freshwater entries are
 * bass/panfish-centric; saltwater entries target inshore species (redfish,
 * trout, snook, flounder, tarpon). The goal is a genuine top-10 pool in every
 * category for both water types, each entry teaching when, why and how to fish
 * it. Extend freely.
 */
export const LURES: LureEntry[] = [
  // =========================================================================
  // FRESHWATER — LURES
  // =========================================================================
  {
    name: 'Lipless Crankbait',
    category: 'lure',
    details: 'Rattletrap-style, 1/2 oz, red craw or chrome/blue; rip it over grass',
    howTo: 'Cast past the grass and reel it back just over the tops; when it ticks the weeds, rip it free — that snap triggers reaction strikes.',
    art: 'lipless',
    waterTypes: ['freshwater'],
    structures: ['vegetation', 'open', 'dropoff'],
    minWaterF: 45,
    maxWaterF: 68,
    skies: ['overcast', 'partly_cloudy'],
    presentation: 'aggressive',
    baseScore: 0.8,
    strength: 'covers water fast and triggers reaction strikes',
    dirtyWaterFriendly: true,
    species: ['largemouth', 'smallmouth', 'pike'],
  },
  {
    name: 'Squarebill Crankbait',
    category: 'lure',
    details: '1.5 size, shad or chartreuse/black back; deflect off cover',
    howTo: 'Reel it steadily and bump it into rock, wood and dock posts; the deflection off cover is what draws the strike, so aim to hit things.',
    art: 'crankbait',
    waterTypes: ['freshwater'],
    structures: ['rock', 'wood', 'open'],
    minWaterF: 50,
    maxWaterF: 75,
    skies: ['overcast', 'partly_cloudy'],
    presentation: 'aggressive',
    baseScore: 0.78,
    strength: 'deflects off rock and wood to draw reaction bites',
    dirtyWaterFriendly: true,
    species: ['largemouth', 'smallmouth'],
  },
  {
    name: 'Spinnerbait',
    category: 'lure',
    details: '3/8 oz, white/chartreuse, willow blades in clear water, Colorado in stain',
    howTo: 'Slow-roll it just under the surface or alongside cover; speed up in warm water, crawl it in cold, and let it helicopter down next to wood.',
    art: 'spinnerbait',
    waterTypes: ['freshwater'],
    structures: ['vegetation', 'wood', 'open'],
    minWaterF: 48,
    maxWaterF: 80,
    skies: ['overcast'],
    presentation: 'aggressive',
    baseScore: 0.75,
    strength: 'flash and vibration shine in wind and low light',
    dirtyWaterFriendly: true,
    species: ['largemouth', 'pike', 'smallmouth'],
  },
  {
    name: 'Topwater Walking Bait',
    category: 'lure',
    details: 'Spook-style, bone or shad; walk-the-dog over flats at dawn/dusk',
    howTo: 'Point the rod tip down and twitch with slack line in a steady rhythm to walk it side to side; pause it near cover and hold on.',
    art: 'topwater-walker',
    waterTypes: ['freshwater', 'saltwater'],
    structures: ['open', 'vegetation'],
    minWaterF: 62,
    maxWaterF: 88,
    skies: ['overcast', 'partly_cloudy'],
    presentation: 'aggressive',
    baseScore: 0.7,
    strength: 'calls fish up in warm water and low light',
    species: ['largemouth', 'smallmouth', 'snook', 'seatrout'],
  },
  {
    name: 'Hollow-Body Frog',
    category: 'lure',
    details: 'Black or white; walk over mats and pads, pause in holes',
    howTo: 'Cast onto mats and pads, walk it across the surface, and pause in every open hole; set the hook hard a full beat after the blow-up.',
    art: 'frog',
    waterTypes: ['freshwater'],
    structures: ['pads', 'vegetation'],
    minWaterF: 65,
    maxWaterF: 90,
    skies: [],
    presentation: 'aggressive',
    baseScore: 0.7,
    strength: 'weedless over heavy vegetation where nothing else goes',
    species: ['largemouth', 'pike'],
  },
  {
    name: 'Buzzbait',
    category: 'lure',
    details: '3/8 oz black or white with a squealing blade; burn it on top',
    howTo: 'Cast past the target and start reeling the instant it lands so the blade churns on the surface the whole way back; keep a steady pace.',
    art: 'buzzbait',
    waterTypes: ['freshwater'],
    structures: ['vegetation', 'wood', 'open'],
    minWaterF: 62,
    maxWaterF: 90,
    skies: ['overcast', 'partly_cloudy'],
    presentation: 'aggressive',
    baseScore: 0.6,
    strength: 'a loud surface bait that calls big fish up in warm, low light',
    species: ['largemouth', 'pike'],
  },
  {
    name: 'Chatterbait (Bladed Jig)',
    category: 'lure',
    details: '3/8 oz green pumpkin or white with paddle-tail trailer',
    howTo: 'Reel at a steady clip so the blade thumps; when it loads up in grass, rip it free — that deflection is what gets bit.',
    art: 'chatterbait',
    waterTypes: ['freshwater'],
    structures: ['vegetation', 'open', 'wood'],
    minWaterF: 50,
    maxWaterF: 80,
    skies: ['partly_cloudy', 'overcast'],
    presentation: 'neutral',
    baseScore: 0.72,
    strength: 'vibration through grass at any speed',
    dirtyWaterFriendly: true,
    species: ['largemouth', 'smallmouth', 'pike'],
  },
  {
    name: 'Jerkbait',
    category: 'lure',
    details: 'Suspending, natural shad; jerk-jerk-pause, long pauses in cold water',
    howTo: 'Jerk the rod tip down twice, then pause; in cold water let it hang motionless for several seconds — most bites come on the pause.',
    art: 'jerkbait',
    waterTypes: ['freshwater'],
    structures: ['open', 'rock', 'dropoff'],
    minWaterF: 38,
    maxWaterF: 60,
    skies: ['partly_cloudy', 'clear'],
    presentation: 'neutral',
    baseScore: 0.7,
    strength: 'long pauses tempt lethargic cold-water fish',
    species: ['smallmouth', 'largemouth', 'walleye'],
  },
  {
    name: 'Swim Jig',
    category: 'lure',
    details: '3/8 oz with swimbait trailer; swim through and around cover',
    howTo: 'Swim it steadily through and around cover with the rod tip up; add an occasional pump-and-pause to imitate a fleeing baitfish.',
    art: 'jig',
    waterTypes: ['freshwater'],
    structures: ['vegetation', 'wood'],
    minWaterF: 52,
    maxWaterF: 82,
    skies: [],
    presentation: 'neutral',
    baseScore: 0.66,
    strength: 'compact profile through scattered cover',
    species: ['largemouth', 'pike'],
  },
  {
    name: 'Football Jig',
    category: 'lure',
    details: '1/2 oz brown/green with craw trailer; drag rock and ledges',
    howTo: 'Drag it slowly across rock and gravel on the bottom; when you feel a ledge or rubble, pause and shake it in place before moving on.',
    art: 'football-jig',
    waterTypes: ['freshwater'],
    structures: ['rock', 'dropoff'],
    minWaterF: 45,
    maxWaterF: 80,
    skies: [],
    presentation: 'neutral',
    baseScore: 0.68,
    strength: 'mimics crawfish along rocky bottoms',
    species: ['smallmouth', 'largemouth'],
  },
  {
    name: 'Paddle-Tail Swimbait',
    category: 'lure',
    details: '3.5-4.5" shad-pattern swimbait on a 1/4-3/8 oz head; steady wind',
    howTo: 'Reel it back at a slow, steady pace so the tail kicks; count it down to fish deeper, and slow-roll it through schools of baitfish.',
    art: 'paddletail',
    waterTypes: ['freshwater'],
    structures: ['open', 'dropoff', 'vegetation'],
    minWaterF: 45,
    maxWaterF: 85,
    skies: [],
    presentation: 'neutral',
    baseScore: 0.66,
    strength: 'a lifelike baitfish profile that catches everything that eats shad',
    species: ['largemouth', 'smallmouth', 'striper', 'walleye'],
  },
  {
    name: 'Inline Spinner',
    category: 'lure',
    details: 'Roostertail-style 1/8-1/4 oz, silver/gold; steady retrieve, swing through current',
    howTo: 'Cast across the current and reel just fast enough to feel the blade spinning; let it swing downstream through likely holding water.',
    art: 'inline-spinner',
    waterTypes: ['freshwater'],
    structures: ['current', 'open', 'rock', 'vegetation'],
    minWaterF: 42,
    maxWaterF: 72,
    skies: [],
    presentation: 'neutral',
    baseScore: 0.6,
    strength: 'flash and thump that trout, panfish and smallmouth chase in moving water',
    species: ['trout', 'panfish', 'smallmouth'],
  },
  {
    name: 'Blade Bait',
    category: 'lure',
    details: '1/4-1/2 oz metal blade; lift-and-drop along deep structure',
    howTo: 'Drop it to the bottom, snap the rod up so it vibrates hard, then let it flutter back down on a controlled line — bites come on the fall.',
    art: 'bladebait',
    waterTypes: ['freshwater'],
    structures: ['dropoff', 'rock', 'open'],
    minWaterF: 35,
    maxWaterF: 55,
    skies: [],
    presentation: 'neutral',
    baseScore: 0.58,
    strength: 'hard vibration that wakes up cold-water fish holding deep',
    dirtyWaterFriendly: true,
    species: ['smallmouth', 'largemouth', 'walleye', 'striper'],
  },

  // =========================================================================
  // FRESHWATER — RIGS
  // =========================================================================
  {
    name: 'Texas-Rigged Soft Plastic',
    category: 'rig',
    details: 'Creature/worm, 3/16-3/8 oz weight, EWG hook; flip to cover',
    howTo: 'Pitch it to cover, let it sink on a tight line, then lift-and-drop it along the bottom; set the hook when you feel a tap or the line jumps.',
    art: 'worm-texas',
    waterTypes: ['freshwater'],
    structures: ['vegetation', 'pads', 'wood'],
    minWaterF: 45,
    maxWaterF: 92,
    skies: ['clear', 'partly_cloudy'],
    presentation: 'finesse',
    baseScore: 0.74,
    strength: 'weedless presentation right in heavy cover',
    species: ['largemouth'],
    pressureFriendly: true,
  },
  {
    name: 'Wacky-Rigged Stickbait',
    category: 'rig',
    details: 'Senko-style, green pumpkin; weightless, let it shimmy down',
    howTo: 'Cast and let it sink on slack line so both ends quiver as it falls, then lift and let it fall again — most bites come as it sinks.',
    art: 'wacky',
    waterTypes: ['freshwater'],
    structures: ['wood', 'open', 'dropoff'],
    minWaterF: 50,
    maxWaterF: 85,
    skies: ['clear', 'partly_cloudy'],
    presentation: 'finesse',
    baseScore: 0.7,
    strength: 'subtle fall that pressured, inactive fish rarely refuse',
    species: ['largemouth', 'smallmouth'],
    pressureFriendly: true,
  },
  {
    name: 'Ned Rig',
    category: 'rig',
    details: '1/10 oz mushroom head, 2.75" stick; drag and deadstick on bottom',
    howTo: 'Cast out, let it settle, then drag it slowly along the bottom with tiny hops and long pauses; keep contact and set on any tick.',
    art: 'ned',
    waterTypes: ['freshwater', 'saltwater'],
    structures: ['rock', 'open', 'dropoff'],
    minWaterF: 38,
    maxWaterF: 75,
    skies: ['clear'],
    presentation: 'finesse',
    baseScore: 0.7,
    strength: 'tiny profile that saves tough, high-pressure days',
    species: ['smallmouth', 'largemouth', 'walleye', 'panfish'],
    pressureFriendly: true,
  },
  {
    name: 'Drop-Shot Rig',
    category: 'rig',
    details: '1/4 oz weight, 4" finesse worm 12-18" up; shake over structure',
    howTo: 'Drop it to the bottom, take up the slack, and shake the rod tip in place so the bait quivers above the weight without swimming away.',
    art: 'dropshot',
    waterTypes: ['freshwater', 'saltwater'],
    structures: ['dropoff', 'rock', 'open'],
    minWaterF: 40,
    maxWaterF: 78,
    skies: ['clear', 'partly_cloudy'],
    presentation: 'finesse',
    baseScore: 0.68,
    strength: 'keeps a bait in the strike zone over deep structure',
    species: ['smallmouth', 'largemouth', 'walleye', 'panfish', 'seatrout'],
    pressureFriendly: true,
  },
  {
    name: 'Curly-Tail Grub on Jighead',
    category: 'rig',
    details: '1/8-1/4 oz head, 2-3" grub (white/chartreuse); cast, count down, swim',
    howTo: 'Cast, count it down to the depth you want, and swim it back steadily so the tail rolls; hop it along the bottom for bonus bites.',
    art: 'grub',
    waterTypes: ['freshwater'],
    structures: ['dropoff', 'open', 'rock', 'wood'],
    minWaterF: 42,
    maxWaterF: 82,
    skies: [],
    presentation: 'finesse',
    baseScore: 0.62,
    strength: 'the most versatile little bait there is for panfish, walleye and bass',
    species: ['panfish', 'walleye', 'smallmouth', 'largemouth'],
    pressureFriendly: true,
  },
  {
    name: 'Carolina Rig',
    category: 'rig',
    details: '1/2-3/4 oz egg weight, bead, swivel, 18-36" leader to a lizard/creature',
    howTo: 'Cast out and drag the weight slowly along the bottom with the rod low, pausing often; the long leader lets the bait float and glide behind.',
    art: 'carolina',
    waterTypes: ['freshwater'],
    structures: ['dropoff', 'rock', 'open'],
    minWaterF: 50,
    maxWaterF: 90,
    skies: [],
    presentation: 'neutral',
    baseScore: 0.64,
    strength: 'covers deep flats and points while keeping the bait near bottom',
    species: ['largemouth', 'smallmouth'],
  },
  {
    name: 'Shaky Head',
    category: 'rig',
    details: '1/8-1/4 oz shaky jighead with a 5-6" finesse worm',
    howTo: 'Cast to cover, let it settle, and shake the rod tip in place so the worm stands up and quivers; drag a few inches and shake again.',
    art: 'shakyhead',
    waterTypes: ['freshwater'],
    structures: ['wood', 'rock', 'dropoff', 'open'],
    minWaterF: 45,
    maxWaterF: 88,
    skies: ['clear', 'partly_cloudy'],
    presentation: 'finesse',
    baseScore: 0.66,
    strength: 'a do-nothing worm that pressured bass almost cannot resist',
    species: ['largemouth', 'smallmouth'],
    pressureFriendly: true,
  },
  {
    name: 'Neko Rig',
    category: 'rig',
    details: 'Stickworm with a nail weight in the head, small wacky hook mid-body',
    howTo: 'Cast and let the weighted nose dive first; lift and drop the rod so the worm stands and shimmies nose-down on the bottom.',
    art: 'wacky',
    waterTypes: ['freshwater'],
    structures: ['rock', 'dropoff', 'wood', 'open'],
    minWaterF: 45,
    maxWaterF: 85,
    skies: ['clear', 'partly_cloudy'],
    presentation: 'finesse',
    baseScore: 0.62,
    strength: 'a nose-down wiggle that triggers bites when nothing else will',
    species: ['smallmouth', 'largemouth'],
    pressureFriendly: true,
  },
  {
    name: 'Tube Rig',
    category: 'rig',
    details: '3-4" tube on an internal 1/8-1/4 oz jighead, green pumpkin',
    howTo: 'Cast to rock, let it spiral down on slack line, then drag and hop it along the bottom; the gliding fall imitates a fleeing crawfish.',
    art: 'tube',
    waterTypes: ['freshwater'],
    structures: ['rock', 'dropoff', 'open'],
    minWaterF: 42,
    maxWaterF: 80,
    skies: ['clear', 'partly_cloudy'],
    presentation: 'finesse',
    baseScore: 0.62,
    strength: 'a darting, crawfish-like glide smallmouth love on rock',
    species: ['smallmouth', 'largemouth'],
    pressureFriendly: true,
  },
  {
    name: 'Punch Rig',
    category: 'rig',
    details: '3/4-1.5 oz pegged tungsten with a compact creature on a stout hook',
    howTo: 'Drop it straight down through matted grass and pads so it punches through the canopy, then let it fall into the open water below and lift.',
    art: 'worm-texas',
    waterTypes: ['freshwater'],
    structures: ['pads', 'vegetation'],
    minWaterF: 60,
    maxWaterF: 92,
    skies: [],
    presentation: 'neutral',
    baseScore: 0.6,
    strength: 'the only way to reach bass buried under heavy matted cover',
    species: ['largemouth'],
  },

  // =========================================================================
  // FRESHWATER — BAIT
  // =========================================================================
  {
    name: 'Nightcrawlers',
    category: 'bait',
    details: 'Split-shot or slip-bobber; classic for panfish, walleye, trout, cats',
    howTo: 'Thread a whole crawler on the hook with a split-shot or under a bobber, leave a wriggling tail, and let it sit or drift slowly.',
    art: 'worm-night',
    waterTypes: ['freshwater'],
    structures: ['open', 'dropoff', 'wood'],
    minWaterF: 38,
    maxWaterF: 85,
    skies: [],
    presentation: 'finesse',
    baseScore: 0.68,
    strength: 'universal confidence bait when the bite is slow',
    dirtyWaterFriendly: true,
    species: ['panfish', 'trout', 'walleye', 'catfish'],
    pressureFriendly: true,
  },
  {
    name: 'Live Minnow under a Slip Float',
    category: 'bait',
    details: 'Crappie minnow on a light wire hook, depth set just above cover',
    howTo: 'Set the float so the minnow rides just above cover, hook it through the back, and watch the float — set the hook when it goes under.',
    art: 'slip-bobber',
    waterTypes: ['freshwater'],
    structures: ['wood', 'dropoff', 'open'],
    minWaterF: 38,
    maxWaterF: 80,
    skies: [],
    presentation: 'finesse',
    baseScore: 0.66,
    strength: 'a struggling minnow is deadly on crappie, walleye and trout',
    species: ['panfish', 'walleye', 'trout'],
    pressureFriendly: true,
  },
  {
    name: 'Live Crayfish',
    category: 'bait',
    details: 'Small craw hooked through the tail; bottom-fished near rock',
    howTo: 'Hook it through the tail or horn, add a small split-shot, and let it crawl along rocky bottom on slack line so it moves naturally.',
    art: 'crayfish',
    waterTypes: ['freshwater'],
    structures: ['rock', 'dropoff', 'wood'],
    minWaterF: 45,
    maxWaterF: 82,
    skies: [],
    presentation: 'finesse',
    baseScore: 0.66,
    strength: 'the number-one natural food for smallmouth and a big-bass favorite',
    species: ['smallmouth', 'largemouth', 'panfish'],
    pressureFriendly: true,
  },
  {
    name: 'Chicken Liver / Stinkbait',
    category: 'bait',
    details: 'Fresh liver or dip-bait on a treble or sponge hook; bottom in current',
    howTo: 'Cast to a deep hole or current seam, let it sit on the bottom, and let the scent draw fish in; set the hook on a steady pull.',
    art: 'dough',
    waterTypes: ['freshwater'],
    structures: ['current', 'dropoff', 'open'],
    minWaterF: 50,
    maxWaterF: 92,
    skies: [],
    presentation: 'finesse',
    baseScore: 0.62,
    strength: 'pure scent that pulls catfish in from a distance in any water',
    dirtyWaterFriendly: true,
    species: ['catfish'],
  },
  {
    name: 'Crickets / Mealworms',
    category: 'bait',
    details: 'Live cricket, mealworm or waxworm on a #8-10 light wire hook',
    howTo: 'Hook one lightly under a small bobber and fish it around brush and docks; twitch it now and then to keep it looking alive.',
    art: 'cricket',
    waterTypes: ['freshwater'],
    structures: ['wood', 'vegetation', 'open'],
    minWaterF: 50,
    maxWaterF: 88,
    skies: [],
    presentation: 'finesse',
    baseScore: 0.6,
    strength: 'irresistible to bluegill and panfish — perfect for kids and slow days',
    species: ['panfish', 'trout'],
    pressureFriendly: true,
  },
  {
    name: 'Dough Bait / PowerBait',
    category: 'bait',
    details: 'Molded floating dough on a small treble, 18-36" above a sliding sinker',
    howTo: 'Mold it onto the hook, cast out, and let the sinker pin it down while the buoyant dough floats up into view; reel the slack tight and wait.',
    art: 'dough',
    waterTypes: ['freshwater'],
    structures: ['open', 'dropoff'],
    minWaterF: 38,
    maxWaterF: 70,
    skies: [],
    presentation: 'finesse',
    baseScore: 0.58,
    strength: 'deadly on stocked trout that key on floating, scented offerings',
    species: ['trout'],
    pressureFriendly: true,
  },
  {
    name: 'Live Bluegill / Sunfish',
    category: 'bait',
    details: 'Small live sunfish on a 2/0-4/0 hook under a float or free-lined (check regs)',
    howTo: 'Hook a lively sunfish through the back, fish it near cover under a big float, and give it room to swim; let a running fish eat before you set.',
    art: 'baitfish',
    waterTypes: ['freshwater'],
    structures: ['wood', 'vegetation', 'dropoff'],
    minWaterF: 55,
    maxWaterF: 90,
    skies: [],
    presentation: 'finesse',
    baseScore: 0.6,
    strength: 'a big live bluegill is trophy bait for bass, pike and flathead catfish',
    species: ['largemouth', 'pike', 'catfish'],
  },

  // =========================================================================
  // SALTWATER — LURES
  // =========================================================================
  {
    name: 'Gold/Silver Spoon',
    category: 'lure',
    details: '1/2 oz weedless gold spoon; steady retrieve over grass flats',
    howTo: 'Cast over grass flats and reel just fast enough to keep the weedless spoon wobbling above the grass; speed up to clear thicker patches.',
    art: 'spoon',
    waterTypes: ['saltwater'],
    structures: ['vegetation', 'open', 'oyster'],
    minWaterF: 60,
    maxWaterF: 88,
    skies: ['partly_cloudy', 'clear'],
    presentation: 'aggressive',
    baseScore: 0.7,
    strength: 'flash that calls redfish across grass flats',
    dirtyWaterFriendly: true,
    species: ['redfish', 'seatrout', 'spanish'],
  },
  {
    name: 'Suspending Twitchbait',
    category: 'lure',
    details: 'MirrOlure-style, natural; twitch-pause over potholes and edges',
    howTo: 'Twitch it down with the rod tip, then pause and let it hang in the strike zone; over cooler water make the pauses longer.',
    art: 'jerkbait',
    waterTypes: ['saltwater'],
    structures: ['dropoff', 'open', 'current'],
    minWaterF: 50,
    maxWaterF: 75,
    skies: ['partly_cloudy', 'clear'],
    presentation: 'neutral',
    baseScore: 0.66,
    strength: 'shines on cooler-water trout that want a slow, suspending target',
    species: ['seatrout', 'snook', 'striper'],
    pressureFriendly: true,
  },
  {
    name: 'Bucktail Jig',
    category: 'lure',
    details: '1/4-1 oz white/chartreuse, optional trailer; hop along the bottom',
    howTo: 'Let it hit the bottom, then hop it back with sharp lifts of the rod and let it fall on a tight line — most bites come as it drops.',
    art: 'bucktail',
    waterTypes: ['saltwater'],
    structures: ['dropoff', 'current', 'open', 'oyster'],
    minWaterF: 45,
    maxWaterF: 85,
    skies: [],
    presentation: 'neutral',
    baseScore: 0.68,
    strength: 'bottom-bouncing classic that flounder, striper and reds eat year-round',
    dirtyWaterFriendly: true,
    species: ['flounder', 'striper', 'redfish', 'snook'],
  },
  {
    name: 'Vertical / Slow-Pitch Jig',
    category: 'lure',
    details: '100-250 g knife or slow-pitch jig, silver/glow/pink; match weight to depth and current',
    howTo: 'Drop it to the bottom over reefs and wrecks, then work it up with sharp rips or slow, rhythmic pitches; most bites come on the fall, so watch the line.',
    art: 'bucktail',
    waterTypes: ['saltwater'],
    structures: ['dropoff', 'rock', 'open'],
    minWaterF: 55,
    maxWaterF: 90,
    skies: [],
    presentation: 'aggressive',
    baseScore: 0.66,
    strength: 'gets down fast to fish holding deep on offshore structure',
    species: ['grouper', 'snapper', 'amberjack', 'tuna', 'kingmackerel'],
  },
  {
    name: 'High-Speed Trolling Spoon',
    category: 'lure',
    details: 'Drone/Clark spoon or heavy casting spoon, silver; wire leader, fast retrieve or troll',
    howTo: 'Cast past feeding fish or troll along color changes and bait schools, and keep it moving fast — pelagics key on speed and flash, not a slow wobble.',
    art: 'spoon',
    waterTypes: ['saltwater'],
    structures: ['open', 'current', 'dropoff'],
    minWaterF: 62,
    maxWaterF: 90,
    skies: ['clear', 'partly_cloudy'],
    presentation: 'aggressive',
    baseScore: 0.62,
    strength: 'speed and flash that mackerel, wahoo and tuna run down',
    species: ['kingmackerel', 'spanish', 'wahoo', 'tuna', 'mahi'],
  },
  {
    name: 'Live Baitfish (Pilchard / Pinfish)',
    category: 'bait',
    details: 'Frisky live pilchard, pinfish, or goggle-eye; circle hook through the nose, stinger for kings',
    howTo: 'Hook it lightly through the nose so it swims naturally, and drift or slow-troll it near structure, weed lines, or bait schools; let the fish eat before coming tight on the circle hook.',
    art: 'baitfish',
    waterTypes: ['saltwater'],
    structures: ['open', 'dropoff', 'rock', 'current'],
    minWaterF: 60,
    maxWaterF: 90,
    skies: [],
    presentation: 'neutral',
    baseScore: 0.7,
    strength: 'the real thing — offshore predators rarely refuse a lively bait',
    species: ['cobia', 'kingmackerel', 'amberjack', 'grouper', 'snapper', 'mahi', 'tarpon'],
  },
  {
    name: 'Soft Plastic Jerkbait',
    category: 'lure',
    details: '4-5" weightless jerk shad (DOA/Slug-Go) on a weighted swimbait hook, natural',
    howTo: 'Twitch the rod tip so it darts side to side, then pause and let it glide and sink; vary the rhythm until the fish show a preference.',
    art: 'paddletail',
    waterTypes: ['saltwater'],
    structures: ['open', 'vegetation', 'mangrove', 'dropoff'],
    minWaterF: 60,
    maxWaterF: 90,
    skies: ['clear', 'partly_cloudy'],
    presentation: 'neutral',
    baseScore: 0.66,
    strength: 'a darting, wounded-baitfish look that snook and trout chase down',
    species: ['snook', 'seatrout', 'redfish', 'tarpon'],
    pressureFriendly: true,
  },
  {
    name: 'Topwater Popper',
    category: 'lure',
    details: 'Cupped-face chugger, bone or mullet; spit and pause over flats',
    howTo: 'Point the rod tip down and give a sharp pull so the cupped face spits water, then pause; repeat — most strikes come right after the splash.',
    art: 'popper',
    waterTypes: ['saltwater'],
    structures: ['open', 'vegetation', 'mangrove', 'oyster'],
    minWaterF: 65,
    maxWaterF: 90,
    skies: ['overcast', 'partly_cloudy'],
    presentation: 'aggressive',
    baseScore: 0.62,
    strength: 'the splash and chug pulls explosive strikes from reds, trout and snook',
    species: ['redfish', 'seatrout', 'snook', 'tarpon'],
  },
  {
    name: 'Lipped Diving Plug',
    category: 'lure',
    details: 'Shallow-diving twitchbait/plug (X-Rap, MirrOdine), natural; twitch-pause',
    howTo: 'Reel it down to its running depth, then twitch and pause so it darts and suspends; work it along potholes, edges and bars.',
    art: 'crankbait',
    waterTypes: ['saltwater'],
    structures: ['dropoff', 'open', 'current', 'oyster'],
    minWaterF: 55,
    maxWaterF: 85,
    skies: ['partly_cloudy', 'clear'],
    presentation: 'neutral',
    baseScore: 0.64,
    strength: 'a tight-wobbling baitfish that covers water and calls fish off structure',
    species: ['seatrout', 'snook', 'spanish', 'striper'],
  },
  {
    name: 'Flair Hawk Jig',
    category: 'lure',
    details: '1/2-1.5 oz nylon flair-hawk jig, white/chartreuse; hop in current',
    howTo: 'Cast up-current and let it sink, then hop it back along the bottom with the flow so it pulses; hold on as it sweeps through the strike zone.',
    art: 'jig',
    waterTypes: ['saltwater'],
    structures: ['current', 'dropoff', 'open'],
    minWaterF: 60,
    maxWaterF: 88,
    skies: [],
    presentation: 'neutral',
    baseScore: 0.6,
    strength: 'the bridge-and-inlet standard for snook and tarpon in moving water',
    dirtyWaterFriendly: true,
    species: ['snook', 'tarpon', 'striper'],
  },
  {
    name: 'Gotcha Plug / Casting Jig',
    category: 'lure',
    details: 'Small chrome casting plug or 1-2 oz jig; fast, erratic retrieve',
    howTo: 'Reel fast and jerk the rod tip in sharp downward sweeps so it darts erratically; keep it moving — the speed is what triggers the strike.',
    art: 'jerkbait',
    waterTypes: ['saltwater'],
    structures: ['current', 'open', 'dropoff'],
    minWaterF: 62,
    maxWaterF: 90,
    skies: ['clear', 'partly_cloudy'],
    presentation: 'aggressive',
    baseScore: 0.58,
    strength: 'fast flash that fires up Spanish mackerel and other speedsters near passes and piers',
    dirtyWaterFriendly: true,
    species: ['spanish', 'seatrout'],
  },

  // =========================================================================
  // SALTWATER — RIGS
  // =========================================================================
  {
    name: 'Soft Plastic Paddletail on Jighead',
    category: 'rig',
    details: '1/4-3/8 oz head, 3-4" paddletail (new penny / chartreuse)',
    howTo: 'Cast, let it sink to the depth you want, then reel steadily so the tail thumps; add a twitch or let it fall near potholes and edges.',
    art: 'paddletail',
    waterTypes: ['saltwater'],
    structures: ['open', 'dropoff', 'current', 'vegetation', 'mangrove', 'oyster'],
    minWaterF: 55,
    maxWaterF: 88,
    skies: [],
    presentation: 'neutral',
    baseScore: 0.8,
    strength: 'the inshore workhorse for reds, trout and flounder',
    species: ['redfish', 'seatrout', 'flounder', 'snook', 'striper'],
    pressureFriendly: true,
  },
  {
    name: 'Popping Cork + Shrimp',
    category: 'rig',
    details: 'Popping cork over 18-30" leader to live or imitation shrimp',
    howTo: 'Cast it out, let it settle, then sharply pop the cork once or twice and pause; the chug imitates feeding fish and calls them in.',
    art: 'popping-cork',
    waterTypes: ['saltwater'],
    structures: ['open', 'current', 'vegetation', 'mangrove', 'oyster'],
    minWaterF: 55,
    maxWaterF: 90,
    skies: [],
    presentation: 'neutral',
    baseScore: 0.78,
    strength: 'the pop calls trout/reds; the cork suspends bait in the strike zone',
    dirtyWaterFriendly: true,
    species: ['seatrout', 'redfish', 'snook'],
  },
  {
    name: 'Soft Plastic Shrimp on Jighead',
    category: 'rig',
    details: 'Imitation shrimp (Gulp!) on a 1/8-1/4 oz jighead; hop near bottom',
    howTo: 'Cast out, let it sink, then hop it slowly along the bottom with short lifts and long pauses; the scent lets you fish it dead-slow.',
    art: 'shrimp',
    waterTypes: ['saltwater'],
    structures: ['open', 'dropoff', 'current', 'oyster', 'vegetation', 'mangrove'],
    minWaterF: 55,
    maxWaterF: 90,
    skies: [],
    presentation: 'finesse',
    baseScore: 0.7,
    strength: 'a scented shrimp you can fish slow and deep when the bite is tough',
    species: ['seatrout', 'redfish', 'flounder', 'snook'],
    pressureFriendly: true,
  },
  {
    name: 'Weedless Weighted Swimbait',
    category: 'rig',
    details: 'Paddletail on a 1/8-1/4 oz weighted weedless swimbait hook; for grass',
    howTo: 'Cast over grass and reel steadily just over the tops so it comes through clean; let it sink into potholes and bump it back to life.',
    art: 'paddletail',
    waterTypes: ['saltwater'],
    structures: ['vegetation', 'mangrove', 'oyster', 'open'],
    minWaterF: 60,
    maxWaterF: 90,
    skies: [],
    presentation: 'neutral',
    baseScore: 0.66,
    strength: 'swims a paddletail through grass and over oysters without fouling',
    species: ['redfish', 'seatrout', 'snook'],
    pressureFriendly: true,
  },
  {
    name: 'Fish-Finder Bottom Rig',
    category: 'rig',
    details: 'Sliding egg sinker above a swivel, 18-36" leader to a 2/0-5/0 circle hook',
    howTo: 'Cast cut or live bait out, let the sinker hold bottom, keep the line just tight, and let the circle hook find the corner of the mouth — do not swing.',
    art: 'bottom-rig',
    waterTypes: ['saltwater'],
    structures: ['current', 'dropoff', 'open', 'oyster'],
    minWaterF: 50,
    maxWaterF: 92,
    skies: [],
    presentation: 'finesse',
    baseScore: 0.68,
    strength: 'the bottom-fishing workhorse for reds, drum and most inshore fish',
    dirtyWaterFriendly: true,
    species: ['redfish', 'flounder', 'striper', 'snook'],
    pressureFriendly: true,
  },
  {
    name: 'Knocker Rig',
    category: 'rig',
    details: 'Egg sinker sliding right down to the hook eye, 2/0-4/0; for structure',
    howTo: 'Pitch it tight to docks, rocks and passes; the weight rides on the hook so you feel bottom and can pull fish out of cover before they break you off.',
    art: 'bottom-rig',
    waterTypes: ['saltwater'],
    structures: ['oyster', 'rock', 'current', 'mangrove'],
    minWaterF: 55,
    maxWaterF: 90,
    skies: [],
    presentation: 'neutral',
    baseScore: 0.62,
    strength: 'keeps bait pinned in heavy structure where snook and reds hide',
    species: ['snook', 'redfish', 'flounder'],
  },
  {
    name: 'Free-Line Rig',
    category: 'rig',
    details: 'Just a hook (and maybe a tiny split-shot) on the leader, live bait',
    howTo: 'Hook a lively bait and cast it out with no weight so it swims naturally; let it roam near cover and feed line to a fish that picks it up.',
    art: 'baitfish',
    waterTypes: ['saltwater'],
    structures: ['mangrove', 'wood', 'open', 'current', 'oyster'],
    minWaterF: 60,
    maxWaterF: 92,
    skies: [],
    presentation: 'finesse',
    baseScore: 0.66,
    strength: 'the most natural way to present live bait to wary snook and trout',
    species: ['snook', 'seatrout', 'redfish', 'tarpon'],
    pressureFriendly: true,
  },

  // =========================================================================
  // SALTWATER — BAIT
  // =========================================================================
  {
    name: 'Live Shrimp',
    category: 'bait',
    details: 'Free-lined or under a cork; hook through the horn',
    howTo: 'Hook it through the horn (avoid the dark spot), free-line it or suspend it under a cork, and let it swim naturally with the current.',
    art: 'shrimp',
    waterTypes: ['saltwater'],
    structures: ['current', 'open', 'dropoff', 'vegetation', 'mangrove', 'oyster'],
    minWaterF: 50,
    maxWaterF: 92,
    skies: [],
    presentation: 'finesse',
    baseScore: 0.82,
    strength: 'almost nothing inshore refuses live shrimp',
    species: ['redfish', 'seatrout', 'snook', 'flounder'],
    pressureFriendly: true,
  },
  {
    name: 'Cut/Live Baitfish',
    category: 'bait',
    details: 'Mullet, menhaden or shad; bottom rig in current, fresh cut on slow days',
    howTo: 'Fish it on a bottom rig in current, or hook a live one through the nose and let it swim; on slow days fresh-cut chunks let the scent do the work.',
    art: 'baitfish',
    waterTypes: ['saltwater', 'freshwater'],
    structures: ['current', 'dropoff', 'open', 'oyster'],
    minWaterF: 40,
    maxWaterF: 92,
    skies: [],
    presentation: 'finesse',
    baseScore: 0.72,
    strength: 'scent does the work when fish are inactive or water is cold/stained',
    dirtyWaterFriendly: true,
    species: ['catfish', 'striper', 'redfish', 'snook', 'flounder', 'tarpon', 'spanish'],
    pressureFriendly: true,
  },
  {
    name: 'Live Pinfish',
    category: 'bait',
    details: 'Lively pinfish on a 2/0-4/0 hook, free-lined or under a cork',
    howTo: 'Hook it through the back or lips and let it swim near grass, docks and bars; its struggle calls big fish — give them a second before you set.',
    art: 'baitfish',
    waterTypes: ['saltwater'],
    structures: ['vegetation', 'wood', 'dropoff', 'open', 'mangrove'],
    minWaterF: 65,
    maxWaterF: 92,
    skies: [],
    presentation: 'finesse',
    baseScore: 0.66,
    strength: 'a hardy live bait that big trout, snook and reds cannot ignore',
    species: ['seatrout', 'snook', 'redfish'],
    pressureFriendly: true,
  },
  {
    name: 'Finger Mullet',
    category: 'bait',
    details: '3-5" live mullet, hooked through the lips or back; free-line or cork',
    howTo: 'Cast it near moving water and bars and let it swim naturally; when a fish takes it and runs, drop the rod, reel tight, and lean into it.',
    art: 'baitfish',
    waterTypes: ['saltwater'],
    structures: ['current', 'dropoff', 'open', 'oyster', 'mangrove'],
    minWaterF: 60,
    maxWaterF: 92,
    skies: [],
    presentation: 'finesse',
    baseScore: 0.7,
    strength: 'the fall mullet run is prime time — almost everything inshore eats them',
    species: ['snook', 'redfish', 'seatrout', 'tarpon', 'flounder'],
    pressureFriendly: true,
  },
  {
    name: 'Blue / Fiddler Crab',
    category: 'bait',
    details: 'Quarter blue crab or whole fiddler on a 2/0-4/0; bottom near structure',
    howTo: 'Pin it to the bottom near oyster bars, bridges and grass and let it sit; reds, drum and sheepshead root them out — set on a steady pull.',
    art: 'crab',
    waterTypes: ['saltwater'],
    structures: ['oyster', 'rock', 'current', 'dropoff', 'mangrove'],
    minWaterF: 55,
    maxWaterF: 90,
    skies: [],
    presentation: 'finesse',
    baseScore: 0.64,
    strength: 'a top natural bait for redfish, black drum, sheepshead and tarpon',
    species: ['redfish', 'tarpon'],
  },
  {
    name: 'Sand Fleas (Mole Crabs)',
    category: 'bait',
    details: 'Live sand flea on a #1-2/0 hook; the surf and around structure',
    howTo: 'Dig them at the wash, hook one through the shell from bottom to top, and cast into the trough or near pilings; let it tumble naturally in the surf.',
    art: 'sandflea',
    waterTypes: ['saltwater'],
    structures: ['current', 'open', 'oyster'],
    minWaterF: 60,
    maxWaterF: 88,
    skies: [],
    presentation: 'finesse',
    baseScore: 0.6,
    strength: 'the number-one surf bait for pompano, and sheepshead and reds love them too',
    species: ['redfish', 'flounder'],
  },
  {
    name: 'Live Croaker',
    category: 'bait',
    details: 'Live croaker on a 3/0-5/0 hook, free-lined or under a cork (summer)',
    howTo: 'Hook it through the back and let it swim near bottom; croakers actually croak, and that sound drives big trout and reds to bite — wait for the run.',
    art: 'baitfish',
    waterTypes: ['saltwater'],
    structures: ['dropoff', 'current', 'open', 'oyster', 'vegetation'],
    minWaterF: 68,
    maxWaterF: 90,
    skies: [],
    presentation: 'finesse',
    baseScore: 0.64,
    strength: 'a summertime big-trout secret — the croak triggers a reaction bite',
    species: ['seatrout', 'redfish', 'snook'],
  },
  {
    name: 'Fresh-Dead / Cut Shrimp',
    category: 'bait',
    details: 'Fresh-dead or chunked shrimp on a 1/0-2/0 hook; bottom or under a cork',
    howTo: 'Thread a piece on so it stays put, fish it on the bottom or under a cork, and let the scent work; great when live bait is hard to get.',
    art: 'shrimp',
    waterTypes: ['saltwater'],
    structures: ['open', 'current', 'dropoff', 'oyster', 'mangrove'],
    minWaterF: 50,
    maxWaterF: 92,
    skies: [],
    presentation: 'finesse',
    baseScore: 0.66,
    strength: 'when nothing else is biting, almost everything inshore will eat dead shrimp',
    dirtyWaterFriendly: true,
    species: ['seatrout', 'redfish', 'flounder', 'snook'],
    pressureFriendly: true,
  },
];
